import React from "react";
import {
  AssignmentRounded,
  AttachMoneyRounded,
  BoltRounded,
  BrushRounded,
  CakeRounded,
  CalculateRounded,
  CalendarMonthRounded,
  CheckCircleRounded,
  ContentCutRounded,
  CreditCardRounded,
  CurrencyPoundRounded,
  DevicesRounded,
  EmailRounded,
  FitnessCenterRounded,
  HourglassBottomRounded,
  LocalDrinkRounded,
  LocalFireDepartmentRounded,
  LinkRounded,
  LocationOnRounded,
  LockRounded,
  MenuBookRounded,
  NotificationsRounded,
  PhoneRounded,
  PaletteRounded,
  PhoneIphoneRounded,
  PlumbingRounded,
  SellRounded,
  SentimentSatisfiedAltRounded,
  SpaRounded,
  StarRounded,
  StorefrontRounded,
  TrendingDownRounded,
  WarningAmberRounded,
  WaterDropRounded,
  WbSunnyRounded,
} from "@mui/icons-material";

const ICONS = {
  assignment: AssignmentRounded,
  barber: ContentCutRounded,
  booking: CalendarMonthRounded,
  brush: BrushRounded,
  cake: CakeRounded,
  calculator: CalculateRounded,
  calendar: CalendarMonthRounded,
  check: CheckCircleRounded,
  devices: DevicesRounded,
  diary: MenuBookRounded,
  drink: LocalDrinkRounded,
  email: EmailRounded,
  energy: BoltRounded,
  fire: LocalFireDepartmentRounded,
  fitness: FitnessCenterRounded,
  hairdresser: SpaRounded,
  lock: LockRounded,
  link: LinkRounded,
  location: LocationOnRounded,
  marketplace: StorefrontRounded,
  money: AttachMoneyRounded,
  notification: NotificationsRounded,
  paint: PaletteRounded,
  payment: CreditCardRounded,
  phone: PhoneIphoneRounded,
  phoneCall: PhoneRounded,
  plumber: PlumbingRounded,
  pound: CurrencyPoundRounded,
  pricingDown: TrendingDownRounded,
  star: StarRounded,
  success: SentimentSatisfiedAltRounded,
  sun: WbSunnyRounded,
  tag: SellRounded,
  time: HourglassBottomRounded,
  warning: WarningAmberRounded,
  water: WaterDropRounded,
};

export default function AppIcon({ name, ...props }) {
  const Icon = ICONS[name] || CheckCircleRounded;
  return <Icon aria-hidden="true" {...props} />;
}
